name: Benchmark

on:
  push:
    branches:
      - 'release*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set branch name
      run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
    - name: Echo branch name
      run: echo ${BRANCH_NAME}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - uses: pnpm/action-setup@v2
      with:
        version: 6.25.0
    - run: npm run setup
    - run: npm run benchmark
  commit:
    needs: build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/add-and-commit@v7
        with:
          add: '. --force'
          message: 'Add benchmark result'
